### PR TITLE
Parse image properties when get image metadata from headers.

### PR DESCRIPTION
**Pull request by RoadRoller**

### CODE REVIEW

**Comment by RoadRoller** [comment]
Looks like that build failed, because it could not fetch source code. How can I restart this build?

**Comment by nacx** [comment]
Just commenting: rebuild please!

**Comment by RoadRoller** [comment]
@nacx thank you!

**Comment by zack-shoylev** [comment]
This is from the official docs:
"There may be multiple headers that begin with the prefix x-image-meta-property-. These headers are free-form key/value pairs that have been saved with the image metadata. The key is the string after x-image-meta-property- and the value is the value of the header"

I would like to have this description added to the code somewhere. However, it seems good as it is.

 +1

**Comment by RoadRoller** [comment]
@zack-shoylev maybe this description can be added to ImageField.PROPERTY enum value?

**Comment by RoadRoller** [comment]
@zack-shoylev comment with description form docs was added.

**Comment by zack-shoylev** [comment]
Squashed, merged, and backported.

**Pull request closed without merging**
