### PR TITLE
Add support for Rackspace Cloud Networks UK

### PR DESCRIPTION
**Pull request by jdaggett**

### CODE REVIEW

**Comment by jdaggett** [comment]
@nacx @zack-shoylev Refactoring these tests is going to take a lot more work than anticipated. I just submitted [JCLOUDS-803](https://issues.apache.org/jira/browse/JCLOUDS-803) to track the issue.

**Comment by zack-shoylev** [comment]
My suggestion would be to fix the remaining review comments (except cleanup-related) then merge, then work on refactoring the tests according to jclouds-803 and make a separate PR. I should be able to help with that.

**Comment by nacx** [comment]
+1. We've commented the data provider approach on IRC and it is definitely a cleaner one and worth implementing, but out of the scope of this PR. I'm ok of addressing that in another PR now that we have a specific issue for that. Let's make it part of the list of things TBD for 1.9.0.

**Comment by zack-shoylev** [comment]
Alright, +1 from me too.
Is there a list in jira for all the 1.9.0 items? There was more than one email with TODOs on the mailing list...

**Comment by jdaggett** [comment]
@nacx @zack-shoylev Thanks! Pushed to **master** e934350

**Pull request closed without merging**
