### PR TITLE
Neutron port ranges only compared when present.

### PR DESCRIPTION
**Pull request by zack-shoylev**

### CODE REVIEW

**Comment by zack-shoylev** [comment]
https://issues.apache.org/jira/browse/JCLOUDS-864

**Comment by nacx** [comment]
+1. Isn't there a live test we can tweak to exercise this?

**Comment by zack-shoylev** [comment]
It can be covered in a mock test. The error happens on our side as a NPE when it does.

**Comment by zack-shoylev** [comment]
Merged and backported

**Pull request closed without merging**
