### PR TITLE
JCLOUDS-691: Remove 404 fallbacks of PUT and POST calls from OpenStac…

### PR DESCRIPTION
**Pull request by devcsrj**
…k APIs

Removed unneeded tests as well from glance, heat, neutron, poppy, marconi.

/cc @zack-shoylev @nacx

### CODE REVIEW

**Comment by devcsrj** [comment]
Amended commit. I accidentally deleted `NetworkApiMockTest`, `SecurityGroupApiMockTest`, `RouterApiMockTest` and `PortApiMockTest` in the previous commit.

Also reverted removal of fallback in [`removeInterfaceForPort`](https://github.com/jclouds/jclouds-labs-openstack/pull/201/files#diff-d3f1d01449178596e90b101c56063c7bR193) (and `*subnet`), despite being `@PUT` operations for it seems like they're actually *delete* operations.

**Comment by nacx** [comment]
LGTM. Good to merge @zack-shoylev?

**Comment by zack-shoylev** [comment]
@nacx @devcsrj +1

This will also have a nice side-effect of speeding builds up a bit.

**Comment by devcsrj** [comment]
Pushed to master as [`167312f`](https://github.com/jclouds/jclouds-labs-openstack/commit/167312fb41997b9add33e409f542fc4a4dcd22cd). Thanks for the reviews!

**Pull request closed without merging**
